on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT2 }}  # ✅ Use PAT instead of default GITHUB_TOKEN

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libcurl4-openssl-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libharfbuzz-dev  \
          libfribidi-dev  \
          libpng-dev      \
          libtiff5-dev \
          libjpeg-dev 

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render Data
        run: Rscript -e 'source("render.R")'

      - name: Commit and Push Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git stash --include-untracked
          git pull origin main --rebase
          git stash pop || echo "No local changes to apply"
          git add .
          git commit -m 'Report updated' || echo "No changes to commit"
          git push origin main  
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT2 }}  
