on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libcurl4-openssl-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libharfbuzz-dev
          libfribidi-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render Data
        run: Rscript -e 'source("render.R")'

      - name: Render and Publish to Netlify
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          render: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
