on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Restore R Package Cache
        run: Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv"); renv::restore()'

      - name: Install packages (Freeze Versions)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::googlesheets4
            any::gt
            any::quarto
          extra-repositories: https://packagemanager.rstudio.com/cran/__linux__/2024-01-01

      - name: Debug - Check files
        run: ls -l

      - name: Render Data
        run: Rscript -e 'source("render.R")'

      - name: Render and Publish to Netlify
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          render: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
